name: "Notify Tests"

on:
  push:
  workflow_dispatch:
  
jobs:

  slack-notify:
    name: 'slack-notify'
    runs-on: ubuntu-latest
    steps:
    - uses: rtCamp/action-slack-notify@v2
      if: always()
      name: 'slack-notify'
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_LEGACY_WEBHOOK_URL }}

    - uses: 8398a7/action-slack@v3
      name: 'action-slack'
      if: always()
      with:
        status: ${{ job.status }}
        # fields: repo,message,commit,author,action,eventName,ref,workflow,job,took,pullRequest # selectable (default: repo,message)
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_INCOMING_WEBHOOK_URL }} # required


    - name: 'slack-send-bot'
      if: always()
      uses: slackapi/slack-github-action@v1.22.0
      with:
        # Slack channel id, channel name, or user id to post message.
        # See also: https://api.slack.com/methods/chat.postMessage#channels
        # You can pass in multiple channels to post to by providing a comma-delimited list of channel IDs.
        channel-id: 'C01FJA0NVJ8'
        # For posting a simple plain text message
        slack-message: "GitHub build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

    - name: 'slack-send-webhook'
      if: always()      
      uses: slackapi/slack-github-action@v1.22.0
      with:
        # Slack channel id, channel name, or user id to post message.
        # See also: https://api.slack.com/methods/chat.postMessage#channels
        payload: |
          {
            "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
                }
              }
            ]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_INCOMING_WEBHOOK_URL }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK


    - name: 'post-slack-message'
      if: always()
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      uses: pullreminders/slack-action@master
      with:
        args: '{\"channel\":\"C01FJA0NVJ8\",\"text\":\"Hello world\"}'


    - name: 'github-action-for-slack'
      if: always()
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_INCOMING_WEBHOOK_URL }}
        SLACK_USERNAME: github-action-for-slack # Optional. (defaults to webhook app)
        #SLACK_CHANNEL: general # Optional. (defaults to webhook)
        SLACK_AVATAR: repository # Optional. can be (repository, sender, an URL) (defaults to webhook app avatar)
      uses: Ilshidur/action-slack@2.0.2
      with:
        args:  |
          {
            "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
                }
              }
            ]
          }

    - name: 'slack-notify-build'
      if: always()
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      uses: voxmedia/github-action-slack-notify-build@v1
      with:
        channel_id: 'C01FJA0NVJ8'
        status: SUCCESS
        color: good